import turtle
tf=("arial",15)
uf=("sanscript",15,"bold")
t=turtle.Turtle()
t.up()
t.goto(0,50)
t.down()
t.write("Turtle: Hi my name is python Turtle",font=tf,align="center")
t.up()
t.goto(0,20)
t.down()
t.write("Turtle: what is your name ",font=tf,align="center")
name=turtle.textinput("Name","What is your name")
name2="Me: My name is "+name
t.up()
t.goto(100,-10)
t.down()
t.write(name2 ,font=uf,align="center")
t.up()
t.goto(0,-30)
t.down()
m="Turtle: "+name+",Where are you from"
t.write(m,font=tf,align="center")
city=name=turtle.textinput("City","What is your City")
city2="I am from "+city
t.up()
t.goto(100,-60)
t.down()
t.write(city2,font=uf,align="center")
t.up()
t.goto(100,-90)
t.down()
t.write("Turtle: Oh thats nice, Welcome to coding with Python",font=tf,align="center") 
turtle.mainloop()