import turtle
name=turtle.textinput("Name","What is your name")
age=turtle.textinput("Age","How old are you")
city=turtle.textinput("City","What is your city")
name=("Name: "+name)
age=("Age: "+age)
city=("City: "+city)
t=turtle.Turtle()
t.color("red")
t.write(name,font=("arial",20,"bold"),align="center")
t.up()
t.goto(0,-50)
t.color("yellow")
t.down()
t.write(age,font=("arial",20,"bold"),align="center")
t.up()
t.goto(0,-100)
t.color("green")
t.down()
t.write(city,font=("arial",20,"bold"),align="center")
t.hideturtle()
turtle.mainloop()