import turtle
name=input("What is your name")
age=input("How old are you")
city=input("what is your city")
name=("Name: "+name)
age=("Age: "+age)
city=("City: "+city)
t=turtle.Turtle()
t.write(name,font=("arial",20,"bold"),align="center")
t.up()
t.goto(0,-50)
t.down()
t.write(age,font=("arial",20,"bold"),align="center")
t.up()
t.goto(0,-100)
t.down()
t.write(city,font=("arial",20,"bold"),align="center")
t.hideturtle()
turtle.mainloop()
